### ISSUE TITLE
no kicad .lib file that i can see

### ISSUE THREAD

**Issue by hbrezner** [jenschr/Teensy3.6-example#1]

**Comment by jenschr** [comment]
Thanks for pointing this out! I've used a CPP .gitignore as a basis. Turns out that's a lousy solution for Kicad...  https://github.com/jenschr/Teensy3.6-example/commit/a13eb4c3c7b769644000e8fa1906eca23670ff19

**Comment by hbrezner** [comment]
as it turns out your mistake may have helped me. i was about to undertake a custom teensy layout, and dreading it, but i revisited the micromod format for teensy 4 and it may fit in my small board space. if it doesn't pan out then i'll be back on your design and roll a custom teensy.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
